#!/usr/bin/env bash

alias q='rlwrap -c -r q'
alias py3='python3'
alias py2='python2'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias rm='rm -I -v'
alias gc='git checkout'
# alias gcommit='git commit --author="NAME <email>"'
